# Generated by Django 5.0.4 on 2024-04-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_tourreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourreview',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
